

 const productArr = [
    {
        name: " Những Tù Nhân  của địa lý ",
        address: 1,
        tag: ["like", "best seller"],
        price : 10000,
        author: "Tim Marshall",
        pulish: "30-11-2020",
        tran: "Phan Linh Lan",
        nxb: "Hội nhà văn",
        page: 432,
        rate: 4,
        category: ["Kinh Tế Chính Trị", "like", "best seller"],
        description: ["“Khi chúng ta đang vươn tới những vì sao, chính bởi những thách thức đặt ra phía trước mà chúng ta có lẽ sẽ phải chung tay để ứng phó: du hành vào vũ trụ không phải với tư cách người Nga, người Trung Quốc hay người Mỹ, mà là những đại diện của nhân loại. Nhưng cho đến nay, mặc dù đã thoát khỏi sự kìm hãm của trọng lực, chúng ta vẫn đang bị giam giữ trong tâm trí của chính mình, bị giới hạn bởi sự nghi ngờ của mình về ‘kẻ khác’, và do đó bởi cuộc cạnh tranh chính yếu về tài nguyên. Phía trước chúng ta còn cả một chặng đường dài.”",
            "“Người Nga vẫn sẽ lo âu dõi mắt về phía tây, nơi có dải đất vẫn còn là bình nguyên, dễ bị xâm nhập; Ấn Độ và Trung Quốc vẫn sẽ bị cách ngăn bởi dãy Himalaya sừng sững, và địa lý sẽ xác định bản chất của những cuộc xung đột giữa hai nước trong tương lai, bất chấp sự phát triển của công nghệ và quân sự; “Đại gia đình châu Âu” đói khát năng lượng, bị phụ thuộc vào những đường ống dẫn dầu từ Nga, và do đó họ không thực sự có nhiều lựa chọn trên bàn đàm phán; sự suy yếu của Hoa Kỳ trong vị thế một siêu cường số một dường như đã bị thổi phồng quá mức, nếu xét tới những lợi thế địa lý mà nước này đã dày công gây dựng…",
            "Và còn rất nhiều dẫn chứng cho thấy vai trò then chốt của các nhân tố địa lý trong bối cảnh chính trị hiện đại. Nhân loại đang trên đường hiện thực hóa giấc mơ vươn vào không gian. Nhưng Tim Marshall vẫn xác quyết rằng: “Các nhân tố địa lý vốn đã góp phần xác định lịch sử đa phần sẽ tiếp tục xác định tương lai của chúng ta”, và rằng: “Địa lý vẫn luôn luôn là một loại nhà tù định nghĩa một quốc gia là gì, hoặc có thể là gì, và là một nhà tù mà các nhà lãnh đạo thế giới thường phải nỗ lực để thoát ra”.",
            "Hay nói cách khác, theo luận điểm của Tim Marshall, thì một thế kỷ nữa kể từ bây giờ, nhân loại vẫn sẽ là “những tù nhân của địa lý”.“Một suy ngẫm cốt lõi và chi tiết về những động lực địa chính trị tồn tại trên toàn cầu.” - Tiến sĩ Sajjan M. Gohel"],
        review: []
    },
    {
        name: " Mùi Hương ",
        address: 2,
        tag: ["like", "best seller"],
        price : 11900,
        author: "Patrick Süskind",
        page: 347,
        pulish: "04-10-2019",
        tran: "Lê Chu Cầu",
        nxb: "Văn học",
        rate: 4,
        category: ["Văn Học Nước Ngoài"],
        description: ["Mùi hương là một cuốn tiểu thuyết ly kỳ về một tên tội phạm đặc biệt.Nhân vật chính của tác phẩm là Jean-Baptise Grenouille, một số phận khác người từ khi mới sinh. Mẹ hắn đã cố tình để mặc hắn chết sặc trông đống ruột cá với mùi máu tanh tưởi. Thế rồi bà ta bị kết án tử hình, còn hắn thì vẫn lớn lên.Hắn có hình dong kỳ dị, và tâm hồn cũng bệnh hoạn. Mọi người ghẻ lạnh, khinh miệt hắn. Hắn đã từng phải sống trong cô độc và đói rét. Nhưng một biệt tài đã giúp cho hắn tìm một con đường sống. Hắn có khả năng khứu giác đặc biệt. Hắn có thể nhận biết, phân biệt và hơn thế, ghi nhớ các mùi hương. Nhờ vào đó, hắn trở thành một thiên tài trong giới sản xuất nước hoa Pháp.Với một đầu óc dị hợm, hắn mơ ước sẽ tạo ra được một hương thơm độc đáo cho riêng mình, một loại nước hoa gợi tình vô song. Và để thoả mãn dục vọng đó, hắn đã săn đuổi mùi hương từ hai mươi lăm trinh nữ…"],
        review: []
    },
    {
        name: " Sức mạnh của người mẹ nhật ",
        address: 3,
        tag: ["like", "best seller"],
        price : 15900,
        author: "An Minjung",
        page: 276,
        pulish: "25-06-2018",
        tran: " Kim Ngân",
        nxb: "Văn học",
        rate: 4,
        category: ["Văn Học Nước Ngoài"],
        description: ["Cuộc đời tác giả Ahn Min Jung bắt đầu thay đổi từ khi gặp người chồng Trung Quốc giỏi tiếng Nhật. Sau nhiều thăng trầm và đi tới kết hôn, cô đã sinh được một bé gái xinh đẹp tên là Lena và bắt đầu nuôi dạy con ở Nhật. Cuốn sách này kể lại hành trình nuôi dạy con mà người mẹ Hàn đích thân trải nghiệm trong quá trình nuôi dạy con gái tại Nhật, được trình bày với sự quan sát và văn phong báo chí đặc trưng của một phóng viên. Những bài tiểu luận dựa trên kinh nghiệm có thực của gia đình chồng Trung vợ Hàn nuôi con tại Nhật đã gây nhiều chú ý trên diễn đàn Naver, khơi gợi sự đồng cảm sâu sắc của các bà mẹ Hàn Quốc ngay từ trước khi xuất bản.",
            "Sức mạnh của người mẹ Nhật sẽ hé lộ nền tảng của phương thức giáo dục ở đất nước sản sinh ra nhiều người đạt giải Nobel nhất châu Á,  không chỉ là câu trả lời cho những bà mẹ đang loay hoay với nhiệm vụ dường như bất khả thi để trở thành người mẹ hoàn hảo, mà còn là những tinh túy chắt lọc từ triết lý sống của người Nhật dành cho những ai quan tâm đến văn hóa Nhật Bản.",
            "“Đây là cuốn sách khiến chúng ta quay lại nhìn và suy ngẫm về văn hóa dạy con của mình.”- SBS News"],
        review: []
    },
    {
        name: " Phía tây không có gì lạ ",
        address: 4,
        tag: ["like", "best seller"],
        price : 15900,
        author: "Erich Maria Remarque",
        page: 248,
        pulish: "2017",
        tran: " Vũ Hương Giang",
        nxb: "Văn học",
        rate: 4,
        category: ["Văn Học Nước Ngoài"],
        description: ["Thế chiến thứ nhất nổ ra, những chàng trai đang ngồi trên ghế nhà trường bị chuyển thẳng ra mặt trận. Tại đây sự khốc liệt của chiến tranh đã khiến họ tê dại khi bom đạn không chỉ tước đi những phần cơ thể mà còn cả tâm hồn. Thế nên chưa kịp trưởng thành họ đã trở nên già nua, bởi gần với cái chết hơn là sự sống. Họ cũng chẳng còn tin tưởng ai, chẳng thiết tha điều gì, kể cả ngày trở về.",
            "Cho nên khi tất cả đồng đội cùng trang lứa đã ngã xuống, cái chết đối với những chàng trai ấy là sự giải thoát. Họ nằm xuống nhẹ nhangfm thanh than đến độ tưởng như chẳng hề may may lay động đến thứ gì xung quanh, dù chỉ là một ngọn cỏ. Mặt trận hoàn toàn yên tĩnh, bản báo cáo chiến trường chỉ ghi vẻn vẹn một câu: “Ở phía Tây, không có gì lạ.” Phải, chẳng có gì lạ, chỉ có một người vừa rời khỏi cuộc đời khi độ tuổi mới chớm đôi mươi."
        ],
        review: []
    },
    {
        name: " Nhà Giả Kim ",
        address: 5,
        tag: ["like", "best seller"],
        price : 16900,
        author: "Paulo Coelho",
        page: 220,
        pulish: "2020",
        tran: " Vũ Hương Giang",
        nxb: "Hội Nhà Văn",
        rate: 4,
        category: ['Thời sự Văn Hóa'],
        description: ["Tiểu thuyết Nhà giả kim của Paulo Coelho như một câu chuyện cổ tích giản dị, nhân ái, giàu chất thơ, thấm đẫm những minh triết huyền bí của phương Đông. Trong lần xuất bản đầu tiên tại Brazil vào năm 1988, sách chỉ bán được 900 bản. Nhưng, với số phận đặc biệt của cuốn sách dành cho toàn nhân loại, vượt ra ngoài biên giới quốc gia, Nhà giả kim đã làm rung động hàng triệu tâm hồn, trở thành một trong những cuốn sách bán chạy nhất mọi thời đại, và có thể làm thay đổi cuộc đời người đọc.",
            "“Nhưng nhà luyện kim đan không quan tâm mấy đến những điều ấy. Ông đã từng thấy nhiều người đến rồi đi, trong khi ốc đảo và sa mạc vẫn là ốc đảo và sa mạc. Ông đã thấy vua chúa và kẻ ăn xin đi qua biển cát này, cái biển cát thường xuyên thay hình đổi dạng vì gió thổi nhưng vẫn mãi mãi là biển cát mà ông đã biết từ thuở nhỏ. Tuy vậy, tự đáy lòng mình, ông không thể không cảm thấy vui trước hạnh phúc của mỗi người lữ khách, sau bao ngày chỉ có cát vàng với trời xanh nay được thấy chà là xanh tươi hiện ra trước mắt. ‘Có thể Thượng đế tạo ra sa mạc chỉ để cho con người biết quý trọng cây chà là,’ ông nghĩ.”",
            "- Trích Nhà giả kim"
        ],
        review: []
    },
    {
        name: " Cha giàu cha nghèo ",
        address: 6,
        tag: "best seller",
        price : 16900,
        author: "	Robert T. Kiyosaki",
        page: 269,
        pulish: "11/12/2012",
        tran: " Vũ Hương Giang",
        nxb: "Plata Publishing",
        rate: 4,
        category: ['Thời sự Văn Hóa', 'Kinh Tế Chính Trị'],
        description: ["Lời tiên tri của người cha giàu sẽ dạy bạn những kỹ năng tài chính cần thiết để chuẩn bị cho bất cứ điều gì sẽ xảy ra; cách thức để tồn tại trong những lúc khủng hoảng - và khám phá ra những đầu tư yêu thích nhất của người cha giàu."],
        review: []
    },
    {
        name: " Onepiece ",
        address: 7,
        tag: "best seller",
        price : 26900,
        author: "Eiichiro Oda",
        page: 200,
        pulish: "1997-NOW",
        tran: " Vũ Hương Giang",
        nxb: "Kim Dong",
        rate: 4,
        category: ["Manga"],
        description: ["Thế giới trong truyện manga One Piece được phác họa trên những vùng biển rộng lớn, tráng lệ nhưng đầy rẫy sự nguy hiểm. Nơi đây diễn ra những trận đánh khốc liệt, gay cấn đến nghẹt thở, với tình đồng đội tạo nên sức mạnh lớn không gì có thể đánh bại.",
            "Một trong những điểm đặc biệt của tập truyện One Piece là cách xây dựng nhân vật độc lạ với hình ảnh của những tên hải tặc vui nhộn đáng yêu. One Piece (Vua hải tặc) bộ thuộc thể loại truyện tranh Hành động kể về một cậu bé tên Monkey D. Luffy, giong buồm ra khơi trên chuyến hành trình tìm kho báu huyền thoại One Piece và trở thành Vua hải tặc nhỏ tuổi. Không chỉ vậy qua ngòi bút của tác giả, Luffy là một hải tặc khét tiếng lại có phần trẻ con, ngây ngô, ham ăn và rất trượng nghĩa phù hợp cho các bạn đọc nhỏ. ",
            "hêm vào đó, mỗi nhân vật phụ xuất hiện xung quanh Luffy cũng được tác giả Oda khắc họa rõ ràng, có tính cách và tài năng riêng biệt, không bị trùng lặp gây nhàm chán. Chính vì vậy ngoại trừ cậu thuyền trưởng Luffy thì những nhân vật phụ trong bộ truyện cũng sở hữu lượng fan hùng hâu."
        ],
        review: []
    },
    {
        name: " Bí Kí Kinh Doanh Của Người Do Thái  ",
        address: 8,
        tag: "",
        price : 19900,
        author: "Minh Tân",
        page: 400,
        pulish: "2021",
        tran: "Minh Tân",
        nxb: "Hồng Đức",
        rate: 4,
        category: ['Kinh Tế Chính Trị', 'Lịch sử - Địa lý'],
        description: ["Một nửa số doanh nhân giàu có trên thế giới là người Do Thái, 1/3 số tỷ phú thế giới là người Do Thái, 18 trong 40 người Mỹ có ảnh hưởng nhất theo xếp hạng của Forbes là người Do Thái, trong 200 người nổi tiếng có ảnh hưởng nhất trên thế giời người Do Thái chiếm một nửa, hơn 20% người đoạt giải Nobel là người Do Thái, 1/3 số giáo sư đại học nổi tiếng thế giới, 60% các nhà văn giỏi nhất cũng là người Do Thái...",
            "Tại sao Israel lại giàu có và trù phú đến vậy đến vậy? Tại sao trí tuệ của người Do Thái lại được lưu truyền nhiều thế hệ như di truyền vậy? ",
            "Lý giải về sự giàu có của người Do Thái có rất nhiều nguyên nhân như:",
            " 1. Người Do Thái thường có quan điểm đúng đắn về tiền bạc. ",
            "2. Họ rất giỏi trong quản lý tài chính và tiếp thị.",
            "3. Người Do Thái giỏi nắm bắt bất kỳ cơ hội kinh doanh nào. ",
            "4. Người Do Thái tuân thủ hợp đồng và đáng tin cậy. ",
            "5. Người Do Thái chú ý đến từ thiện.",
            "   Nhưng lý giải về sự xuất sắc của người Do Thái chỉ có một nguyên nhân duy nhất: Người Do Thái rất coi trọng giáo dục và học tập. Do đó, từ thời thơ ấu cha mẹ Do Thái đã chú trọng nuôi dạy con cái, tôn trọng trí tuệ và coi trọng việc nuôi dưỡng tư duy và tài năng của trẻ. ",
            "   Trí tuệ làm giàu là cuốn sách trình bày các khía cạnh của sự khôn ngoan mà dân tộc Do Thái sở hữu. Hãy cùng suy ngẫm về sự giàu có và trí thông minh của họ. Cuốn sách có thể được coi là tóm lược về các công cụ tích lũy tài sản và các công cụ tư duy được những người Do Thái nổi tiếng toàn cầu như gia tộc Rothschild, Rockefeller, Buffett, Bill Gates và Soros sử dụng hàng bao năm qua."
        ],
        review: []
    },
    {
        name: " Gió thổi mùa trăng năm ấy ",
        address: 9,
        tag: "",
        price : 9900,
        author: "Vạn Lý Độc Hành",
        page: 288,
        pulish: "2022",
        tran: "Vạn Lý Độc Hành",
        nxb: "Hội Nhà Văn",
        rate: 4,
        category: ["Văn Học Nước Ngoài", 'Văn Học Việt Nam'],
        description: ["“Gió Thổi Mùa Trăng Năm Ấy” là những mảnh ký được kể lại bằng một “giọng điệu “ văn chương dung dị đầy hài hước, rất đời, nhưng cũng vô cùng ấm áp.",
            "Gió thổi mùa trăng năm ấy khơi gợi lại trong lòng người đọc biết bao kỉ niệm đẹp về một thời thanh xuân căng đầy nhựa sống, với không ít những khờ dại trong tình yêu, cùng những “trận chiến” bất tận của đám thanh niên mầm mới lớn, chỉ vì muốn mình trở thành “người hùng” trong đôi mắt cô bạn học xinh đẹp."
            , "Bạn đọc sẽ có nhiều bất ngờ thú vị bởi sự miêu tả tinh tế về “mảnh đất tình quê” thân thương; những hoài niệm tuổi thơ, tình bạn học trò mà “ai cũng thấy bóng dáng mình trong đó.",
            "Vui nhộn, hài hước, hấp dẫn đến từng chi tiết. Ấm áp, lãng mạn, day dứt trong từng con chữ.",
            "Gió thổi mùa trăng năm ấy như một bức thư tình gửi cho tuổi trẻ, gửi cho Hà Nội của một thời đã xa."
        ],
        review: []
    },
    {
        name: " Đọc Vị Bất Kỳ Ai ",
        address: 10,
        tag: ["like"],
        price : 17900,
        author: "David J Lieberman",
        page: 223,
        pulish: "2019",
        tran: "Đại Học Kinh Tế Quốc Dân",
        nxb: "Lao Động",
        rate: 4,
        category: ['Thời sự Văn Hóa'],
        description: ["Trong Đọc vị bất kì ai - để không bị lừa dối và lợi dụng, với đầy ắp những thủ thuật tâm lý được trình bày tỉ mỉ mà bạn có thể áp dụng với bất cứ ai hay bất kì tình huống nào, Tiến sĩ David Lieberman trao cho bạn khả năng giành được những gì bạn muốn bất cứ khi nào bạn cần. Không chỉ là các chiến lược hay nguyên tắc, trong cuốn sách này còn có rất nhiều giải pháp cho những vấn đề kinh doanh của bạn. Và bạn sẽ được trang bị những công cụ tối ưu để điều hành doanh nghiệp của mình.",
            "Hãy chiếm thế thượng phong trong việc chủ động nhận biết điều cần tìm kiếm – ở bất kỳ ai bằng cách “thâm nhập vào suy nghĩ” của người khác. Đọc vị bất kỳ ai là cẩm nang dạy bạn cách thâm nhập vào tâm trí của người khác để biết điều người ta đang nghĩ. Cuốn sách này sẽ không giúp bạn rút ra các kết luận chung về một ai đó dựa vào cảm tính hay sự võ đoán. Những nguyên tắc được chia sẻ trong cuốn sách này không đơn thuần là những lý thuyết hay mẹo vặt chỉ đúng trong một số trường hợp hoặc với những đối tượng nhất định. Các kết quả nghiên cứu trong cuốn sách này được đưa ra dựa trên phương pháp S.N.A.P – cách thức phân tích và tìm hiểu tính cách một cách bài bản trong phạm vi cho phép mà không làm mếch lòng đối tượng được phân tích. Phương pháp này dựa trên những phân tích về tâm lý, chứ không chỉ đơn thuần dựa trên ngôn ngữ cử chỉ, trực giác hay võ đoán.",
            "Nhà lãnh đạo ưu tú không chỉ là người đưa ra quyết định đúng đắn hay chiến lược gia tài ba. Họ phải nắm bắt được những kỹ năng mà không phải trường kinh doanh nào cũng dạy – đó là sức mạnh của thuyết phục và thấu hiểu. Qua cuốn sách làm sếp không chỉ là nghệ thuật, bạn sẽ làm chủ được những thủ thuật tâm lý để thuyết phục mọi người quanh mình và tạo được một liên minh vững chắc."
        ],
        review: []
    },
    {
        name: " Khéo Ăn khéo Nói Sẽ Có Được Thiên Hạ ",
        address: 11,
        tag: ['Thời sự Văn Hóa'],
        price : 15900,
        author: "Trác Nhã",
        page: 403,
        pulish: "2022",
        tran: "Nguyễn Phương Thảo",
        nxb: "Đại Học Sư Phạm",
        rate: 4,
        category: ["Văn Học Nước Ngoài"],
        description: ["Trong xã hội thông tin hiện đại, sự im lặng không còn là vàng nữa, nếu không biết cách giao tiếp thì dù là vàng cũng sẽ bị chôn vùi. Trong cuộc đời một con người, từ xin việc đến thăng tiến, từ tình yêu đến hôn nhân, từ tiếp thị cho đến đàm phán, từ xã giao đến làm việc... không thể không cần đến kĩ năng và khả năng giao tiếp. Khéo ăn khéo nói thì đi đâu, làm gì cũng gặp thuận lợi. Không khéo ăn nói, bốn bề đều là trở ngại, khó khăn. Trong thời đại thông tin và liên lạc phát triển nhanh chóng, tin tức được cập nhật liên tục, các công cụ thông tin và kĩ thuật truyền thông được ứng dụng rộng rãi như ngày nay thì việc khéo ăn nói đã trở thành “cái tài số một thiên hạ”. Trong khoảng thời gian ngắn nhất, nếu ai có thể nêu bật được khả năng, thực lực của mình cho đối phương biết thì đó sẽ là người chiến thắng. Chính vì vậy mà câu nói “Khéo ăn nói sẽ có được thiên hạ” rất có ý nghĩa. Vậy, như thế nào mới gọi là biết cách ăn nói? Nói năng lưu loát, không ấp úng có được gọi là biết cách nói chuyện không? Nói ngắn gọn, nói ít nhưng ý nghĩa thâm sâu có được gọi là biết cách nói chuyện không? Hay nhất định phải nói nhiều mới là biết nói chuyện?",
            "Trong cuộc sống thường ngày, chúng ta thấy rằng: Biết cách nói chuyện không nhất định là phải nói nhiều, quan trọng là phải nói đúng trọng tâm, đúng nội dung. Và điều quan trọng là phải nắm được vấn đề mình đang nói đến. Chắc chắn rất nhiều người đã gặp phải tình huống như thế này: Có những nhân viên tiếp thị khi gặp khách hàng thì giống như một cái máy, nói không ngừng nghỉ, không để ý tới phản ứng và cảm nhận của khách hàng, không cần biết vị khách đó có đang nghe lời giới thiệu về sản phẩm hay không. Nếu làm việc như vậy thì người đó nắm chắc phần thất bại. Trong cuộc sống và trong công việc, chúng ta cũng rất hay gặp phải hiện tượng như sau: Nhiều người khi nói chuyện với người quen thì nói rất hay, không bị mất bình tĩnh hay ấp úng. Thế nhưng khi gặp người lạ hoặc phải nói chuyện trong một đám đông, thì người đó dường như bị mất sự chủ động với ngôn ngữ, có lúc còn không biết mình đã nói gì. Vậy làm thế nào để cải thiện và tránh gặp phải những tình huống như trên? Làm thế nào để ăn nói khéo léo? Có phương pháp và quy luật nào được áp dụng khi giao tiếp không? Có nguyên tắc và bí quyết nào cho các cuộc nói chuyện không? Trong những tình huống khác nhau, với những người khác nhau thì phải nói chuyện như thế nào, và làm sao để trình bày những điều khó nói?",
            "Cuốn sách “Khéo ăn nói sẽ có được thiên hạ” này sẽ giải đáp những câu hỏi đó. Cuốn sách với ngôn từ rõ ràng, gần gũi với cuộc sống sẽ mang đến những kĩ năng và phương pháp giao tiếp thực dụng, chắc chắn sẽ giúp ích cho quý độc giả. Nếu như những quy tắc và phương pháp chỉ giúp một số ít người nắm được và ứng dụng, thì giá trị của nĩ là có hạn. Chỉ cần những quy tắc và phương pháp cuốn sách đưa ra giúp được nhiều người, thì giá trị của nó là vơ hạn. Tác giả của “Khéo ăn nói sẽ có được thiên hạ” đã dốc hết tâm sức nghiên cứu về các kĩ năng và quy tắc giao tiếp, đây cũng chính là giá trị lớn nhất của cuốn sách."
            , "Một cuốn sách hay sẽ tự nói lên được giá trị của nó, và tự bản thân mỗi độc giả sẽ cảm nhận được điều đó. Quý độc giả sẽ tự nhiên yêu thích một cuốn sách có thể chạm đến trái tim và bổ ích cho mình. Còn với một cuốn sách không hay, độc giả sẽ không mua và cũng sẽ không để tâm đến. Sự hay dở của một cuốn sách do chính độc giả cảm nhận và xác định, thị trường sách cũng sẽ có đánh giá. Cuối cùng, nhắc lại về vấn đề giao tiếp, tôi có hai điều muốn nói với độc giả: Thứ nhất là nói chuyện phải chân thành. Chân thành chính là thứ ngôn ngữ hay nhất, nếu không chân thành thì cho dù nói nhiều bao nhiêu, nắm được nhiều kĩ năng và phương pháp giao tiếp đến thế nào, tất cả cũng chỉ là vô nghĩa. Điều thứ hai là phải lắng nghe bằng trái tim. Chỉ có lắng nghe bằng trái tim thì chúng ta mới biết phải nói gì, nói như thế nào. Những người không biết cách lắng nghe thì không phải là người biết cách nói chuyện. Người biết cách nói chuyện thì chắc chắn là người biết lắng nghe."
        ],
        review: []
    },
    {
        name: " Nghệ Thuật Từ Chối ",
        address: 12,
        tag: ['Thời sự Văn Hóa'],
        price : 21900,
        author: "Damon Zahariades",
        page: 160,
        pulish: "2020",
        tran: "	Ngô Tâm",
        nxb: "Hồng Đức",
        rate : 4,
        category : ["Văn Học Nước Ngoài"],
        description:["Học cách nói “Không” cũng là yêu chính mình. Sẽ có lúc bạn nhận ra: Làm vừa lòng thiên hạ là một chuyện vừa khó lại vừa ngu!!",
        "Từ chối một ai đó bằng việc nói “KHÔNG” ngay lập tức thì thật sỗ sàng. Chính vì vậy mà cách từ chối khéo không để lại “SẸO” luôn được nhiều người quan tâm.",
        "Vậy làm sao để có kỹ năng từ chối mà không mất lòng người khác, không làm rạn nứt mối quan hệ và cả hai người đều không cảm thấy khó xử? Bizbooks xin trân trọng gửi đến quý độc giả cuốn sách: “Nghệ Thuật Từ Chối – Cách Nói Không Mà Vẫn Có Được Đồng Thuận”",
        "Nghệ Thuật Từ Chối – Cách Nói Không Mà Vẫn Có Được Đồng Thuận",
        "Bí quyết đưa ra lời Từ chối mà không làm tổn hại các mối quan hệ nằm “Nghệ Thuật Từ Chối – Cách Nói Không Mà Vẫn Có Được Đồng Thuận” giúp bạn tìm hiểu nguyên nhân và đưa ra cách từ chối “nhẹ nhàng”. Cuốn sách chia quy trình Từ chối thành những bước như- Chuẩn bị từ chối, đưa ra từ chối và hoàn tất từ chối – cuốn sách hướng dẫn bạn phương pháp nói Không hiệu quả, mạnh mẽ nhất, bạn có thể thực hiện ngay trong đời sống, công việc và các mối quan hệ.",
        "Nguyên nhân hàng đầu khiến cho việc từ chối trở nên khó khăn, là bạn không có nguyên tắc rõ ràng. Do đó, bạn càng nhanh chóng lập ra một danh sách “nhất quyết nói không” sớm bao nhiêu, mọi sự sẽ càng trở nên dễ dàng bấy nhiêu.",
        "Để giữ được hiệu quả làm việc của mình và giảm tối đa căng thẳng trong công việc, bạn nhất thiết phải học cách nói không sao cho nhẹ nhàng lịch sự – một điều mà rất nhiều người trong chúng ta không thể làm được.",
        "Chỉ có luyện tập mới có thể giúp bạn mài giũa kỹ năng tới hoàn thiện. Nói “không” thường xuyên sẽ giúp bạn dần dần biết cách từ chối khéo léo hơn, đồng thời khiến bạn quen dần với điều này. Đôi khi bạn phải nói đi nói lại để có thể truyền tải thông điệp của mình tới những người cố chấp. Nếu họ cứ khăng khăng nhờ bạn làm việc này việc kia, hãy nhấn mạnh lời từ chối nhiều lần. Cuối cùng họ cũng phải hiểu ra và rời đi.",
        "Những chỉ dẫn trong cuốn sách Nghệ Thuật Từ Chối – Cách Nói Không Mà Vẫn Có Được Đồng Thuận sẽ là cẩm nang tuyệt vời giúp bạn thiết lập những mối quan hệ gắn bó mà bản thân không cảm thấy áp lực. "
    ],
        review : []
    },
    {
        name: " 21 Bài học cho thế kỷ 21 ",
        address: 13,
        tag: ['Thời sự Văn Hóa',"moi"],
        price : 21900,
        author: "Yuval Noah Harari",
        page: 224,
        pulish: "02-10-2019",
        tran: "Dương Ngọc Trà",
        nxb: "Thế Giới",
        rate : 4,
        category : ["Văn Học Nước Ngoài"],
        description:["Sau khi tìm hiểu quá khứ và tương lai của nhân loại qua hai cuốn sách gây tiếng vang là Sapiens và Homo deus, Yuval Noah Harari đi sâu vào các vấn đề “ngay tại đây” và “ngay lúc này”, tức các sự kiện hiện tại và tương lai gần nhất của xã hội loài người.",
        "Những triển vọng đầy hứa hẹn của công nghệ sẽ được đưa ra bàn luận bên cạnh những hiểm họa như “đứt gãy” do công nghệ gây ra, việc kiểm soát thế giới bên trong dẫn tới sự sụp đổ của hệ thần kinh hay “tự do trong khuôn khổ”. Chính trị và tôn giáo có còn bắt tay nhau như trong quá khứ hay sẽ thao túng con người theo những cách riêng rẽ, mới mẻ hơn? Và những vấn đề toàn cầu ấy liên quan mật thiết tới hành vi và đạo đức của từng cá nhân riêng lẻ như thế nào? Xét cho cùng, những thách thức lớn nhất và những lựa chọn quan trọng nhất của ngày nay là gì? Ta cần chú ý đến điều gì? Ta nên dạy con cái ta những gì?",
        "“Cuộc khủng hoảng sinh thái đang lấp ló, mối đe dọa của các loại vũ khí hủy diệt hàng loạt [...] và sự trỗi dậy của các công nghệ đột phá mới” là những nỗi lo không của riêng ai; và Harari sẽ đồng hành cùng bạn trên con đường bóc tách từng vấn đề một cách thấu đáo."
    ],
        review : []
    },
    {
        name: " Lược Sử Tôn Giáo ",
        address: 14,
        tag : ["new"],
        price : 31900,
        author: " RICHARD HOLLOWAY",
        page: 308,
        pulish: "12-09-2019",
        tran: " Loan Vũ",
        nxb: "Thế Giới",
        rate : 4,
        category : ["Văn Học Nước Ngoài"],
        description:["Sau khi tìm hiểu quá khứ và tương lai của nhân loại qua hai cuốn sách gây tiếng vang là Sapiens và Homo deus, Yuval Noah Harari đi sâu vào các vấn đề “ngay tại đây” và “ngay lúc này”, tức các sự kiện hiện tại và tương lai gần nhất của xã hội loài người.",
        "Những triển vọng đầy hứa hẹn của công nghệ sẽ được đưa ra bàn luận bên cạnh những hiểm họa như “đứt gãy” do công nghệ gây ra, việc kiểm soát thế giới bên trong dẫn tới sự sụp đổ của hệ thần kinh hay “tự do trong khuôn khổ”. Chính trị và tôn giáo có còn bắt tay nhau như trong quá khứ hay sẽ thao túng con người theo những cách riêng rẽ, mới mẻ hơn? Và những vấn đề toàn cầu ấy liên quan mật thiết tới hành vi và đạo đức của từng cá nhân riêng lẻ như thế nào? Xét cho cùng, những thách thức lớn nhất và những lựa chọn quan trọng nhất của ngày nay là gì? Ta cần chú ý đến điều gì? Ta nên dạy con cái ta những gì?",
        "“Cuộc khủng hoảng sinh thái đang lấp ló, mối đe dọa của các loại vũ khí hủy diệt hàng loạt [...] và sự trỗi dậy của các công nghệ đột phá mới” là những nỗi lo không của riêng ai; và Harari sẽ đồng hành cùng bạn trên con đường bóc tách từng vấn đề một cách thấu đáo."
    ],
        review : []
    },
    {
        name: " Toán Học Một Chương Tiểu Thuyết ",
        address: 15,
        tag: "best seller",
        price : 32900,
        author: "Mickaël Launay",
        page: 332,
        pulish: "16-05-2019",
        tran: " Nhã phong",
        nxb: "Thế Giới",
        rate : 4,
        category : ["Văn Học Nước Ngoài"],
        description:["Hầu hết mọi người đều thích toán, tiếc là họ không biết điều này!",
        "Bởi ai mà chẳng thấy hấp dẫn với những mẩu chuyện kỳ thú về toán: như “giáo phái” toán học kỳ lạ của Pythagoras thời cổ đại hay những cuộc thăm dò hệ mặt trời bằng công cụ toán học đầy kịch tính thời cận đại, hoặc gần đây hơn là sự kiện máy tính AlphaGo giành chiến thắng trước kỳ thủ cờ vây số một thế giới Lee Sedol bằng những nước đi “thần thánh” sử dụng lý thuyết xác suất.",
    "Toán học khai sinh vì lý do hữu dụng, hẳn nhiên. Vào thời tiền sử, người ta nghĩ ra những con số để đếm đàn gia súc, dùng hình học để đo ruộng đất, làm đường sá. Loài home sapiens chúng ta không ngừng tò mò muốn khám phá thế giới tự nhiên xung quanh, nên suốt mấy ngàn năm qua toán học đã tiến lên phía trước với những bước khổng lồ và ngày càng trừu tượng.",
    "Mickaël Launaykhông chỉ cho người đọc thấy cái đẹp, chất thơ của toán học mà còn xác quyết một điều khác, rằng mọi người đều có thể yêu thích toán học và đều có thể cảm nhận được vẻ đẹp tự nhiên của nó. Cuốn sách này là một minh chứng cho điều đó."
    ],
        review : []
    },
    {
        name: " Lịch Sử Chiến Tranh",
        address: 16,
        tag : "",
        price : 31900,
        author: "John Keegan",
        page: 620,
        pulish: "19-11-2018",
        tran: "Thiếu Khanh",
        nxb: "Lao động",
        rate : 4,
        category : ["Văn Học Nước Ngoài"],
        description:["Chiến tranh là văn minh hay dã man? Trả lời câu hỏi tưởng như dễ này, không dễ. Loài người ngày càng văn minh hơn, ngày càng nhiều khám phá khoa học gây sốc hơn và nhiều phát minh khó ngờ hơn, song chẳng phải vì vậy mà các cuộc chiến tranh ít đi. Ngược lại, chiến tranh vẫn tiếp tục, và sự tàn bạo của chiến tranh không hề giảm bớt - có chăng, chiến tranh chỉ ngày càng đa dạng, tinh vi hơn, khả năng giết người càng khủng khiếp hơn. Vậy loài người cần dựa vào đâu, cần có những gì để bảo đảm rằng các thế hệ tương lai sẽ chứng kiến một thế giới tuy vẫn còn quân đội nhưng sẽ ít chiến tranh hơn và vạn nhất chiến tranh có xảy ra, nó sẽ được kiểm soát tốt hơn, ít tàn bạo hơn?",
        "Lịch sử chiến tranh của John Keegan là một tác phẩm công phu và quả cảm nhằm tìm câu trả lời không dễ cho những câu hỏi đó",
        "“Keegan là sử gia quân sự đương đại vừa dễ đọc nhất vừa độc sáng nhất. Lịch sử chiến tranh có lẽ là công trình nghiên cứu về chiến tranh đáng kể nhất từ xưa đến nay.”",
        "- The New York Times Book Review"
        ],
        review : []
    },
    {
        name: " Phía Sau Cuộc Chiến  ",
        address: 17,
        tag: ["best seller","like"],
        price : 11900,
        author: "Deborah Nelson",
        page: 340,
        pulish: "12-05-2010",
        tran: "Deborah Nelson",
        nxb: "Thông Tấn",
        rate : 4,
        category : ["Văn Học Nước Ngoài"],
        description:["Tháng 2 năm 1968, một tháng trước cuộc thảm sát tai tiếng ở Mỹ Lai, một đơn vị lính Mỹ ở miền Trung Việt Nam đi càn qua một ngôi làng nhỏ, bắt được mười chín người dân không có vũ trang – bao gồm phụ nữ, trẻ em, thiếu niên và một người đàn ông lớn tuổi. Hôm đó, toán lính nhận được mệnh lệnh “giết sạch những gì di động”. Họ dồn dân làng vào nơi trống trải rồi nã đạn. Sau vụ việc, thanh tra lục quân đội lấy lời khai có tuyên thệ của hàng tá binh sĩ, thu thập được nhiều chi tiết ám ảnh miêu tả lại cuộc thảm sát. Tuy nhiên, vụ việc bị chìm xuồng, không ai bị kết tội.",
        " Những lời khai đó – và ghi nhận của hàng trăm cựu chiến binh Mỹ khác từng chứng kiến các vụ thảm sát, giết chóc, cưỡng hiếp, tra tấn – được Ban tham mưu lục quân Mỹ những năm 1970 đưa vào diện hồ sơ đặc biệt cần lưu trữ bí mật và cất kỹ suốt ba mươi năm. Giờ đây được giải mật, những hồ sơ thu thập các báo cáo về tội ác chiến tranh của quân đội Mỹ ở Việt Nam ít ai biết đã hé lộ với công chúng. Hồ sơ bao gồm cả những vụ việc đã được chứng minh liên can đến hơn 300 lời cáo buộc, liên đới đến thành viên mọi sư đoàn lớn từng tham gia cuộc chiến.",
        "Năm 2005, nhà báo đoạt giải Pulitzer Deborah Nelson và nhà sử học quân sự Nicholas Turse cùng hợp tác tìm hiểu sự thật phía sau những chồng hồ sơ. Phía sau cuộc chiến miêu tả quá trình cả hai đi tìm câu trả lời từ những người bị cáo buộc phạm vào tội ác chiến tranh, từ những nhân chứng cáo buộc và cả các quan chức cấp cao đã che giấu sự thật.",
        " Cùng với những cái nhìn chân thực gây sốc khác được tiết lộ về những hành động của binh lính Mỹ tham chiến ở Iraq và Afghanistan gần đây, Phía sau cuộc chiến nhìn thẳng vào những bí mật đen tối nhất về cuộc chiến ở Việt Nam.",
        ],
        review : []
    },
    {
        name: " Truyền Kì Mạn Lục ",
        address: 18,
        tag: "like",
        price : 14900,
        author: " Nguyễn Dữ",
        page: 254,
        pulish: "20-12-2018",
        tran: "Trúc Khê",
        nxb: "Hội nhà văn",
        rate : 4,
        category : ["Văn Học Nước Ngoài"],
        description: ["“Bộ sách Truyền kỳ mạn lục ông Nguyễn Dữ viết theo lối văn trong sách ‘Tiễn đăng tân thoại’ của Tàu... Toàn bộ văn viết có những chỗ biện luận hùng hồn, có những chỗ điêu khắc tỉ mỉ, chỗ tươi đẹp như bức tranh màu lộng lẫy, chỗ vang dội như dòng suối chảy lô xô; các truyện phần nhiều có thơ hay đoạn văn tứ lục chen vào mà những thơ văn đó đều là mỹ diệm tiêm tế lắm... Bộ sách này, về phần văn chương... đời Lê đã khen là ‘thiên cổ kỳ bút.’",
        "Uống nước trong và ở thác biếc, mặc thây danh lợi không bận gì đến. Hang đá bên mây cất mình dễ, màn bụi trên đời vướng chân khó.","Giữa khoảng đời hỗn loạn cuối Lê, người ta đã phảng phất thấy ở Nguyễn Dữ tiên sinh cái phong cách Đào Uyên Minh đời Tấn.”",
        "- TRÚC KHÊ"],
        review : []
    },
    {
        name: " Tắt Đèn ",
        address: 19,
        price : 19000,
        author: "Ngô Tất Tố",
        page: 231,
        pulish: "30-07-2018",
        tran: " Vũ Hương Giang",
        nxb: "Hội nhà văn",
        rate : 4,
        category : ["Văn Học Nước Ngoài"],
        description: ["“Đánh ‘xoảng’ một cái, cái bát ở mâm lý cựu bay thẳng sang mâm lý đương. Và đánh ‘chát’ một cái, cái chậu ở chiếu lý đương cũng đập luôn vào cây cột bên cạnh lý cựu. Nước canh, nước mắm bắn ra tứ tung. Hết thảy mọi người đều lố nhố đứng dậy…",
        "Chánh tổng sực tan giấc mộng, ngơ ngác hỏi giật hỏi giọng:",
        "- Cái gì thế? Cái gì thế? Nốc cho lắm rồi nói bậy! Người nào gây chuyện với người nào?”"
        ],
        review : []
    },
    {
        name: " Nhật Kí Đặng Thùy Trâm ",
        address: 20,
        price : 11900,
        author: "Đặng Thùy Trâm",
        page: 296,
        pulish: "24-06-2022",
        tran: " Vũ Hương Giang",
        nxb: "Hội nhà văn",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description:["Một cuốn nhật kí nhặt được bên xác của một nữ Việt Cộng đã suýt bị người lính Mỹ ném vào lửa, nhưng người phiên dịch đã khuyên anh ta nên giữ lại vì ‘trong đó có lửa’. Nhật kí Đặng Thùy Trâm là những ghi chép hàng ngày của một người nữ bác sĩ về cuộc sống của chị nơi chiến tuyến. Cuốn nhật kí là thế giới riêng của người trí thức nhạy cảm mà không yếu đuối, tha thiết với cuộc sống mà không hề sợ hãi trước những gian nan. Ở đó ta vẫn gặp những băn khoăn trăn trở trước tình yêu, trước cuộc sống phức tạp hàng ngày, những nỗi buồn, nỗi nhớ nhung, sự cô đơn của một người con gái, nhưng đồng thời chúng ta cũng thấy được một ý chí mãnh liệt, những lời nói tự động viên cảnh tỉnh, một lòng can đảm phi thường - những điều đã làm nên một thế hệ anh hùng."
    ],
        review : []
    },
    {
        name: " Lặng Yên Cho Nước Chảy",
        address: 21,
        tag : "",
        price : 11900,
        author: " Mai Văn Phấn",
        page: 120,
        pulish: "13-03-2018",
        tran: " Vũ Hương Giang",
        nxb: "Hội nhà văn",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description: ["“Chiều nay em cho con bú. Ngoài kia từng chân kiến đang đi, từng cánh ong vẫn còn đang vỗ. Nơi anh về trú ngụ là ô trời xanh trong mắt em cười. Hạnh phúc nào bằng ta bên nhau thảnh thơi, như được xoải mình nơi chân đê cát mịn. Anh hôn lên ngực em căng đầy thơm mát, chiều ngọt ngào cánh cò cánh vạc, qua môi anh khẽ đậu xuống hồn. Căn phòng mình chẳng còn những bức tường bao quanh và không gian thành thời gian thánh thiện, khi anh mải mê nhìn vầng ngực em dâng đầy như biển, cứ thu mình tìm vào miệng con be bé xinh xinh...”"],
        review : []
    },
    {
        name: " Ngoại ô ",
        address: 22,
        author: " Nguyễn Đình Lập",
        price : 14900,
        page: 234,
        pulish: "23-08-2017",
        tran: " Vũ Hương Giang",
        nxb: "Hội nhà văn",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description: ["“Cũng như mọi buổi sáng tinh mơ khác, khi những giọt sương khuya hãy còn rả rích lăn trên tầu lá, rồi lại từ tầu lá rơi đánh bộp xuống đường ẩm ướt, thì ở đây, ở cái cửa ô tối tăm và chật hẹp này, lòng yêu sống, mong sống, ham sống bắt đầu lôi kéo bao nhiêu kiếp người vào một cuộc sinh hoạt gay go, tàn nhẫn và nhọc nhằn.”"],
        review : []
    },
    {
        name: " Chúc Mẹ ngủ Ngon ",
        address: 23,
        tag: ["moi"],
        price : 17900,
        author: "Mi-ae Seo",
        page: 396,
        pulish: "10-11-2020",
        tran: "Nguyễn Thị Hồng Hà",
        nxb: "Hà Nội",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description: ["Cuộc sống vốn yên ả của nhà tâm lý học tội phạm Lee Sun Kyung bỗng chốc lệch quỹ đạo khi hai biến cố bất ngờ và bất thường cùng lúc ập tới. Vào ngày Sun Kyung nhận nhiệm vụ phỏng vấn một tên tội phạm giết người hàng loạt, chồng cô dẫn về nhà con gái riêng mười một tuổi, nạn nhân sống sót duy nhất trong vụ hỏa hoạn cướp đi mạng sống tất cả người thân trong gia đình cô bé.",
        "Hai số phận như chẳng liên quan với nhau đột nhiên song hành cùng dẫn Sun Kyung về một hướng - nơi ranh giới giữa công việc và gia đình, lý trí và tình cảm, lý thuyết và thực tiễn đều bị xóa nhòa, chỉ để lại một mê cung hỗn loạn mà lối thoát cuối cùng chưa hẳn đã là giải thoát...",
        "Chúc mẹ ngủ ngon hứa hẹn là cuốn sách một khi đã cầm lên thì khó lòng đặt xuống để yên giấc, đến từ một trong những tác giả trinh thám kinh dị hàng đầu Hàn Quốc."
        ],
        review : []
    },
    {
        name: " Donquixote ",
        address: 24,
        tag : ["best seller","like","moi"],
        price : 31900,
        author: "Jonathan Bousmar",
        page: 160,
        pulish: "14-05-2018",
        tran: " Phong Thu",
        nxb: "Văn học",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description:  ["“Don Quixote khởi đầu như một tỉnh lẻ, trở thành Tây Ban Nha, và cuối cùng như một vũ trụ.”- V. S. Pritchell",
        "“Có thể nói mọi tiểu thuyết văn xuôi đều là biến tấu trên chủ đề Don Quixote.”- Lionell Trilling",
        "“Cervantes là người sáng lập Thời Hiện đại... Tiểu thuyết gia không cần trả lời ai ngoài Cervantes. Thực sự không thể hình dung nổi Don Quixote như một con người bằng xương bằng thịt, nhưng trong tâm trí của chúng ta, còn có nhân vật nào sống động hơn?”- Milan Kundera",
    "Don Quixote, tiểu thuyết hay nhất mọi thời đại, được dịch ra nhiều thứ tiếng nhất và được tái bản nhiều nhất trong lịch sử nhân loại, chỉ sau Kinh Thánh."       ],
        review : []
    },
    {
        name: " Bản Chất Của Người ",
        address: 25,
        tag: "like",
        price : 15900,
        author: "Han Kang",
        page: 350,
        pulish: "30-08-2019",
        tran: "Kim Ngân",
        nxb: "Hà Nội",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description:  ["“Bây giờ, tôi xin được hỏi anh.",
        "Như vậy, có phải con người là một sinh vật tàn nhẫn từ trong bản chất? Hay đó chỉ là những trải nghiệm phổ biến của chúng ta? Có phải chúng ta chỉ đang sống trong ảo tưởng về phẩm giá con người, còn thực ra bất cứ lúc nào, chúng ta cũng có thể biến thành một thứ chẳng là gì cả, thành sâu bọ, thành thú vật, thành một đống mủ dịch lẫn lộn? Bỉ sỉ nhục, bị bôi nhọ, bị tàn sát, phải chăng đó là bản chất của con người đã được chứng minh trong lịch sử?",
        "Tôi đang chiến đấu. Ngày nào tôi cũng một mình chiến đấu. Tôi chiến đấu với nỗi nhục nhã vì mình đã sống sót, và vì mình vẫn còn đang sống tiếp. Tôi chiến đấu với sự thật rằng mình cũng là con người. Tôi chiến đấu với ý nghĩ rằng chỉ có cái chết mới là con đường duy nhất có thể kéo tôi thoát khỏi sự thật đó. Cùng là con người với nhau, anh có thể cho tôi một câu trả lời không?”",
        "Bản chất của người,với sự kiện lịch sử Phong trào dân chủ Gwangju (1980) làm bối cảnh chính, được đánh giá là một trong những tiểu thuyết xuất sắc và giàu sức lay động nhất của Han Kang, được chính tác giả thừa nhận là “tác phẩm mà tôi không thể trốn tránh, không thể không viết, nếu không viết, không vượt qua, có lẽ tôi sẽ không thể đi tiếp đến bất cứ đâu.”"
        ],
        review : []
    },
    {
        name: " Những Kẻ Bày Mưu ",
        address: 26,
        tag : ["best seller", "like"],
        price : 18900,
        author: "Kim Un Su",
        page: 444,
        pulish: "27-09-2019",
        tran: "Thanh Phương",
        nxb: "Hà Nội",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description:["“Nghĩ lại thì ai bắn cũng chẳng quan trọng. Vấn đề cốt lõi luôn là người đứng đằng sau kẻ bắn.”",
        "Bị bỏ rơi ngay khi vừa chào đời, Lai Sinh được Lão Chồn nuôi lớn tại Thư viện của lũ chó - đại bản doanh của những bộ não giỏi bày mưu nhất thế giới ngầm Hàn Quốc. Lớn lên giữa những mưu đồ tanh máu và những nhân vật động thủ không gớm tay, số phận buộc Lai Sinh trưởng thành làm một sát thủ, một mắt xích máy móc trong chuỗi sinh tồn quy mô và quy củ không lối thoát. Nhưng khi những người thân cận và chính bản thân trở thành mục tiêu của những kẻ bày mưu, Lai Sinh liệu còn lựa chọn nào khác ngoài tự tay phá vỡ mọi quy tắc, vén lớp màn về đám người luôn đứng sau nhét súng vào tay mình?",
        "Tham vọng trong xây dựng một thế giới ngầm hư cấu mà chân thực, linh hoạt trong xây dựng tuyến nhân vật rộng mà vẫn có chiều sâu, Những kẻ bày mưu là một trong những best-seller hấp dẫn nhất của văn học Hàn Quốc những năm gần đây, khó có thể đặt xuống khi ta đã mở trang đầu tiên."
    ],
        review : []
    },
    {
        name: " Tiệm Bánh Ngọt Lúc Nửa Đêm ",
        address: 27,
        tag:[ "best seller", "like"],
        price : 18900,
        author: "Hoàng Mặc Kỳ",
        page: 540,
        pulish: "20-09-2019",
        tran: "Mai Dung",
        nxb: "Hà Nội",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description:["Có một truyền thuyết thành thị kể rằng:",
        "Ở một góc khuất của thành phố, có một tiệm bánh ngọt, chỉ mở cửa lúc nửa đêm, không những bán đồ ngọt, mà còn trao đổi bí mật. Bạn tìm đến, kể cho các chủ tiệm câu chuyện của mình, họ sẽ vén bức màn lên, tiết lộ với bạn một bí mật. Trong mỗi món đồ ngọt đều ẩn giấu một bí mật không ai hay biết, trong mỗi bí mật có lẽ lại có một phần con người bạn.",
        "Bánh ngọt lịm, kem thơm dịu, còn bí mật đa phần là đắng cay và nước mắt. Bạn có dám nếm thử vị ngọt the đắng ấy không?"
        ],
        review : []
    },
    {
        name: " Hoa Hồng Sa Mạc ",
        address: 28,
        tag: ["best seller","like"],
        price : 19000,
        author: "Luis Sepúlveda",
        page: 204,
        pulish: "22-08-2019",
        tran: "Lâm An",
        nxb: "Hội nhà văn",
        rate : 4,
        category : ["Văn Học Việt Nam"],
        description:["“Nghĩ lại thì ai bắn cũng chẳng quan trọng. Vấn đề cốt lõi luôn là người đứng đằng sau kẻ bắn.”",
        "Bị bỏ rơi ngay khi vừa chào đời, Lai Sinh được Lão Chồn nuôi lớn tại Thư viện của lũ chó - đại bản doanh của những bộ não giỏi bày mưu nhất thế giới ngầm Hàn Quốc. Lớn lên giữa những mưu đồ tanh máu và những nhân vật động thủ không gớm tay, số phận buộc Lai Sinh trưởng thành làm một sát thủ, một mắt xích máy móc trong chuỗi sinh tồn quy mô và quy củ không lối thoát. Nhưng khi những người thân cận và chính bản thân trở thành mục tiêu của những kẻ bày mưu, Lai Sinh liệu còn lựa chọn nào khác ngoài tự tay phá vỡ mọi quy tắc, vén lớp màn về đám người luôn đứng sau nhét súng vào tay mình?",
        "Tham vọng trong xây dựng một thế giới ngầm hư cấu mà chân thực, linh hoạt trong xây dựng tuyến nhân vật rộng mà vẫn có chiều sâu, Những kẻ bày mưu là một trong những best-seller hấp dẫn nhất của văn học Hàn Quốc những năm gần đây, khó có thể đặt xuống khi ta đã mở trang đầu tiên."
    ],
        review : []
    },
]

module.exports = productArr;
